[package]
name = "wasm-bindgen-derive-macro"
description = "Proc-macro backend for wasm-bindgen-derive"
categories = ["no-std", "wasm"]
license.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
trybuild = "1"
wasm-bindgen-derive = { workspace = true }
