[package]
name = "wasm-bindgen-derive"
description = "Trait derivation macros for wasm-bindgen"
categories = ["no-std", "wasm"]
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-derive-macro = { workspace = true }
